week-4/music-concert-network/config/routes.rb
Rails.application.routes.draw do
  root :to => "concerts#index"
  resources :concerts, except: [:index]
end

week-4/music-concert-network/app/models/concert.rb
class Concert < ActiveRecord::Base
  validates :artist, presence: true
  validates :venue, presence: true
  validates :city, presence: true
  validates :date, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  has_attached_file :asset, styles: { medium: "300x300>", thumb: "100x100>", small: "64X64>" }, default_url: "/assets/missing_:style.jpg"
  validates_attachment_content_type :asset, content_type: /\Aimage\/.*\Z/

  def self.today
    where("date = ?", Date.today)
  end

  def self.upcoming
    where("date > ?", Date.today)
  end

  def self.this_month
    upcoming.where("date <= ?", Date.today.end_of_month)
  end
end

week-4/music-concert-network/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
    @today_concerts = Concert.today
    @this_month_concerts = Concert.this_month
  end
  def show
    @concert = Concert.find_by(id: params[:id])
  end
  def new
    @concert = Concert.new
  end
  def create
    @concert = Concert.new(concert_params)
    if @concert.valid?
      @concert.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def concert_params
    params.require(:concert).permit(:artist, :venue, :city, :price, :date, :description, :asset)
  end
end

week-4/music-concert-network/app/helpers/concerts_helper.rb
module ConcertsHelper
end

week-4/music-concert-network/app/views/concerts/_form.html.erb
<%= form_for @concert do |f| %>
  <div class="form-group">
    <%= f.label :artist %>
    <%= f.text_field :artist, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :venue %>
    <%= f.text_field :venue, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :asset %>
    <%= f.file_field :asset %>
    <p class="help-block">Upload an artist image</p>
  </div>

  <%= f.submit "save", class: "btn btn-default" %>
<% end %>

week-4/music-concert-network/app/views/concerts/index.html.erb
<div class="container-fluid">
  <div class="row">
    <section class="concerts col-md-10">
      <div class="row">
        <h2>just happening</h2>
      </div>
        <div class="container-fluid">
          <% @today_concerts.each do |concert| %>
            <%= link_to concert_path(concert) do %>
              <article class="col-xs-6 col-md-4 col-lg-3">
                <div class="img-container">
                  <span class="vertical-align"></span>
                  <%= image_tag concert.asset.url(:medium) %>
                </div>
                <h4><%= concert.artist %> @ <%= concert.city %></h4>
                <h5><%= concert.date.strftime("%e %b %y") %></h5>
                <p>
                  <%= truncate(concert.description,  :length => 80,
                                                      :separator => " ",
                                                      :omission => "... (view more)") %>
                </p>
              </article>
            <% end %>
          <% end %>
        </div>
    </section>
    <aside class="col-md-2">
      <h3>this month</h3>
      <ul class="media-list">
        <% @this_month_concerts.each do |concert| %>
          <li class="media">
            <div class="media-left">
              <%= link_to(concert_path(concert)) do %>
                <%= image_tag concert.asset.url(:small), class: "media-object" %>
              <% end %>
            </div>
            <div class="media-body">
              <p>
                <%= concert.artist %>
              </p>
            </div>
          </li>
        <% end %>
      <ul>
    </aside>
  </div>
</div>

week-4/music-concert-network/app/views/concerts/new.html.erb
<h2>Add concert</h2>
<%= render "layouts/errors", model: @concert  %>
<%= render "form" %>

week-4/music-concert-network/app/views/concerts/show.html.erb
<article class="concert-detail">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-5">
        <%= image_tag @concert.asset.url(:medium) %>
      </div>
      <div class="col-md-7">
        <h2><%= @concert.artist %></h2>
        <h3>
          <%= @concert.city %> -
          <%= @concert.date.strftime("%e %b %y") %>
        </h3>
        <h4>
          (<%= @concert.venue %>)
        </h4>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <i class="fa fa-money" aria-hidden="true"></i>
        <span><strong>Price: </strong></span>
        <span><%= @concert.price %></span>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p><%= @concert.description %></p>
      </div>
    </div>
  </div>
</article>